### ISSUE TITLE
Corrections to spec

### ISSUE THREAD

**Issue by apt1002** [rrthomas/mite#2]
Things noticed while reading the spec.

**Comment by apt1002** [comment]
Registers and memory: "M s (a) denotes the s bytes in memory starting at byte a; a must be a multiple of W" <-- should say "a multiple of s".

**Comment by apt1002** [comment]
Labels "There types of label are" <-- !

**Comment by apt1002** [comment]
Computation: "n is subtracted from W on a big-endian Mite" <-- W-w

**Comment by apt1002** [comment]
Data: "Data between two labels are stored contiguously in M." <-- What about padding to achieve alignment?

**Comment by rrthomas** [comment]
Definitely should be "n is subtracted from W-1": "w" is not a quantity here, it's a flag.
